inherit_from: [configs/dataset/config_base_3RScan_full_l160.yaml, configs/method/config_base_JointSSG.yaml]
training:
 data_workers: 2 # This method requires more RAM usage. If you have 64 GB Ram you can remove this.
model:
 multi_rel: true # multiple relationship
wandb:
 tags: ["ssg", "jointSSG",'full','l160']
