inherit_from: [configs/dataset/config_base_3RScan_orbslam_l20.yaml,configs/method/config_base_VGfM.yaml]
model:
 multi_rel: false # multiple relationship 
wandb:
 dry_run: false
 tags: ["ssg", "vgfm",'orbslam','l20']
